name: PHP Linting (Pint)
on: [push, pull_request]
jobs:
  phplint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: psr12
          verboseMode: true
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Style Change (Laravel Pint in CI)
          skip_fetch: true
